/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module test_32bit(x, s, clk, r);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  input clk;
  output [31:0] r;
  input s;
  input [31:0] x;
  sky130_fd_sc_hd__mux2_1 _32_ (
    .A0(r[1]),
    .A1(x[1]),
    .S(s),
    .X(_11_)
  );
  sky130_fd_sc_hd__mux2_1 _33_ (
    .A0(r[2]),
    .A1(x[2]),
    .S(s),
    .X(_22_)
  );
  sky130_fd_sc_hd__mux2_1 _34_ (
    .A0(r[3]),
    .A1(x[3]),
    .S(s),
    .X(_25_)
  );
  sky130_fd_sc_hd__mux2_1 _35_ (
    .A0(r[4]),
    .A1(x[4]),
    .S(s),
    .X(_26_)
  );
  sky130_fd_sc_hd__mux2_1 _36_ (
    .A0(r[5]),
    .A1(x[5]),
    .S(s),
    .X(_27_)
  );
  sky130_fd_sc_hd__mux2_1 _37_ (
    .A0(r[6]),
    .A1(x[6]),
    .S(s),
    .X(_28_)
  );
  sky130_fd_sc_hd__mux2_1 _38_ (
    .A0(r[7]),
    .A1(x[7]),
    .S(s),
    .X(_29_)
  );
  sky130_fd_sc_hd__mux2_1 _39_ (
    .A0(r[8]),
    .A1(x[8]),
    .S(s),
    .X(_30_)
  );
  sky130_fd_sc_hd__mux2_1 _40_ (
    .A0(r[9]),
    .A1(x[9]),
    .S(s),
    .X(_31_)
  );
  sky130_fd_sc_hd__mux2_1 _41_ (
    .A0(r[10]),
    .A1(x[10]),
    .S(s),
    .X(_01_)
  );
  sky130_fd_sc_hd__mux2_1 _42_ (
    .A0(r[11]),
    .A1(x[11]),
    .S(s),
    .X(_02_)
  );
  sky130_fd_sc_hd__mux2_1 _43_ (
    .A0(r[12]),
    .A1(x[12]),
    .S(s),
    .X(_03_)
  );
  sky130_fd_sc_hd__mux2_1 _44_ (
    .A0(r[13]),
    .A1(x[13]),
    .S(s),
    .X(_04_)
  );
  sky130_fd_sc_hd__mux2_1 _45_ (
    .A0(r[14]),
    .A1(x[14]),
    .S(s),
    .X(_05_)
  );
  sky130_fd_sc_hd__mux2_1 _46_ (
    .A0(r[15]),
    .A1(x[15]),
    .S(s),
    .X(_06_)
  );
  sky130_fd_sc_hd__mux2_1 _47_ (
    .A0(r[16]),
    .A1(x[16]),
    .S(s),
    .X(_07_)
  );
  sky130_fd_sc_hd__mux2_1 _48_ (
    .A0(r[17]),
    .A1(x[17]),
    .S(s),
    .X(_08_)
  );
  sky130_fd_sc_hd__mux2_1 _49_ (
    .A0(r[18]),
    .A1(x[18]),
    .S(s),
    .X(_09_)
  );
  sky130_fd_sc_hd__mux2_1 _50_ (
    .A0(r[19]),
    .A1(x[19]),
    .S(s),
    .X(_10_)
  );
  sky130_fd_sc_hd__mux2_1 _51_ (
    .A0(r[20]),
    .A1(x[20]),
    .S(s),
    .X(_12_)
  );
  sky130_fd_sc_hd__mux2_1 _52_ (
    .A0(r[21]),
    .A1(x[21]),
    .S(s),
    .X(_13_)
  );
  sky130_fd_sc_hd__mux2_1 _53_ (
    .A0(r[22]),
    .A1(x[22]),
    .S(s),
    .X(_14_)
  );
  sky130_fd_sc_hd__mux2_1 _54_ (
    .A0(r[23]),
    .A1(x[23]),
    .S(s),
    .X(_15_)
  );
  sky130_fd_sc_hd__mux2_1 _55_ (
    .A0(r[24]),
    .A1(x[24]),
    .S(s),
    .X(_16_)
  );
  sky130_fd_sc_hd__mux2_1 _56_ (
    .A0(r[25]),
    .A1(x[25]),
    .S(s),
    .X(_17_)
  );
  sky130_fd_sc_hd__mux2_1 _57_ (
    .A0(r[26]),
    .A1(x[26]),
    .S(s),
    .X(_18_)
  );
  sky130_fd_sc_hd__mux2_1 _58_ (
    .A0(r[27]),
    .A1(x[27]),
    .S(s),
    .X(_19_)
  );
  sky130_fd_sc_hd__mux2_1 _59_ (
    .A0(r[28]),
    .A1(x[28]),
    .S(s),
    .X(_20_)
  );
  sky130_fd_sc_hd__mux2_1 _60_ (
    .A0(r[29]),
    .A1(x[29]),
    .S(s),
    .X(_21_)
  );
  sky130_fd_sc_hd__mux2_1 _61_ (
    .A0(r[30]),
    .A1(x[30]),
    .S(s),
    .X(_23_)
  );
  sky130_fd_sc_hd__mux2_1 _62_ (
    .A0(r[31]),
    .A1(x[31]),
    .S(s),
    .X(_24_)
  );
  sky130_fd_sc_hd__mux2_1 _63_ (
    .A0(r[0]),
    .A1(x[0]),
    .S(s),
    .X(_00_)
  );
  sky130_fd_sc_hd__dfxtp_1 _64_ (
    .CLK(clk),
    .D(_10_),
    .Q(r[19])
  );
  sky130_fd_sc_hd__dfxtp_1 _65_ (
    .CLK(clk),
    .D(_12_),
    .Q(r[20])
  );
  sky130_fd_sc_hd__dfxtp_1 _66_ (
    .CLK(clk),
    .D(_13_),
    .Q(r[21])
  );
  sky130_fd_sc_hd__dfxtp_1 _67_ (
    .CLK(clk),
    .D(_14_),
    .Q(r[22])
  );
  sky130_fd_sc_hd__dfxtp_1 _68_ (
    .CLK(clk),
    .D(_15_),
    .Q(r[23])
  );
  sky130_fd_sc_hd__dfxtp_1 _69_ (
    .CLK(clk),
    .D(_16_),
    .Q(r[24])
  );
  sky130_fd_sc_hd__dfxtp_1 _70_ (
    .CLK(clk),
    .D(_17_),
    .Q(r[25])
  );
  sky130_fd_sc_hd__dfxtp_1 _71_ (
    .CLK(clk),
    .D(_18_),
    .Q(r[26])
  );
  sky130_fd_sc_hd__dfxtp_1 _72_ (
    .CLK(clk),
    .D(_19_),
    .Q(r[27])
  );
  sky130_fd_sc_hd__dfxtp_1 _73_ (
    .CLK(clk),
    .D(_20_),
    .Q(r[28])
  );
  sky130_fd_sc_hd__dfxtp_1 _74_ (
    .CLK(clk),
    .D(_21_),
    .Q(r[29])
  );
  sky130_fd_sc_hd__dfxtp_1 _75_ (
    .CLK(clk),
    .D(_23_),
    .Q(r[30])
  );
  sky130_fd_sc_hd__dfxtp_1 _76_ (
    .CLK(clk),
    .D(_24_),
    .Q(r[31])
  );
  sky130_fd_sc_hd__dfxtp_1 _77_ (
    .CLK(clk),
    .D(_00_),
    .Q(r[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _78_ (
    .CLK(clk),
    .D(_11_),
    .Q(r[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _79_ (
    .CLK(clk),
    .D(_22_),
    .Q(r[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _80_ (
    .CLK(clk),
    .D(_25_),
    .Q(r[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _81_ (
    .CLK(clk),
    .D(_26_),
    .Q(r[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _82_ (
    .CLK(clk),
    .D(_27_),
    .Q(r[5])
  );
  sky130_fd_sc_hd__dfxtp_1 _83_ (
    .CLK(clk),
    .D(_28_),
    .Q(r[6])
  );
  sky130_fd_sc_hd__dfxtp_1 _84_ (
    .CLK(clk),
    .D(_29_),
    .Q(r[7])
  );
  sky130_fd_sc_hd__dfxtp_1 _85_ (
    .CLK(clk),
    .D(_30_),
    .Q(r[8])
  );
  sky130_fd_sc_hd__dfxtp_1 _86_ (
    .CLK(clk),
    .D(_31_),
    .Q(r[9])
  );
  sky130_fd_sc_hd__dfxtp_1 _87_ (
    .CLK(clk),
    .D(_01_),
    .Q(r[10])
  );
  sky130_fd_sc_hd__dfxtp_1 _88_ (
    .CLK(clk),
    .D(_02_),
    .Q(r[11])
  );
  sky130_fd_sc_hd__dfxtp_1 _89_ (
    .CLK(clk),
    .D(_03_),
    .Q(r[12])
  );
  sky130_fd_sc_hd__dfxtp_1 _90_ (
    .CLK(clk),
    .D(_04_),
    .Q(r[13])
  );
  sky130_fd_sc_hd__dfxtp_1 _91_ (
    .CLK(clk),
    .D(_05_),
    .Q(r[14])
  );
  sky130_fd_sc_hd__dfxtp_1 _92_ (
    .CLK(clk),
    .D(_06_),
    .Q(r[15])
  );
  sky130_fd_sc_hd__dfxtp_1 _93_ (
    .CLK(clk),
    .D(_07_),
    .Q(r[16])
  );
  sky130_fd_sc_hd__dfxtp_1 _94_ (
    .CLK(clk),
    .D(_08_),
    .Q(r[17])
  );
  sky130_fd_sc_hd__dfxtp_1 _95_ (
    .CLK(clk),
    .D(_09_),
    .Q(r[18])
  );
endmodule
