/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module test3(D, rstn, en, clk, q);
  wire [3:0] _0_;
  input [3:0] D;
  input clk;
  input en;
  output [3:0] q;
  input rstn;
  sky130_fd_sc_hd__mux2_1 _1_ (
    .A0(q[1]),
    .A1(D[1]),
    .S(en),
    .X(_0_[1])
  );
  sky130_fd_sc_hd__mux2_1 _2_ (
    .A0(q[2]),
    .A1(D[2]),
    .S(en),
    .X(_0_[2])
  );
  sky130_fd_sc_hd__mux2_1 _3_ (
    .A0(q[3]),
    .A1(D[3]),
    .S(en),
    .X(_0_[3])
  );
  sky130_fd_sc_hd__mux2_1 _4_ (
    .A0(q[0]),
    .A1(D[0]),
    .S(en),
    .X(_0_[0])
  );
  sky130_fd_sc_hd__dfrtp_1 _5_ (
    .CLK(clk),
    .D(_0_[0]),
    .Q(q[0]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _6_ (
    .CLK(clk),
    .D(_0_[1]),
    .Q(q[1]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _7_ (
    .CLK(clk),
    .D(_0_[2]),
    .Q(q[2]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _8_ (
    .CLK(clk),
    .D(_0_[3]),
    .Q(q[3]),
    .RESET_B(rstn)
  );
endmodule
